#!/usr/bin/env python3
"""Generate a SOLAR arch YAML for AMD Instinct parts at an arbitrary locked clock.

Why a generator and not a hand-written YAML:

SOLAR's arch config mixes two kinds of quantity, and they scale differently
when you change the locked clock:

  * MAC_per_cycle_*   -- ARCHITECTURAL. Fixed by the matrix-core datapath
                         width. Frequency-INDEPENDENT. Do not touch when
                         F_LOCK changes.
  * *_byte_per_cycle  -- DERIVED. Real bandwidth is fixed in bytes/second
                         (HBM runs on its own clock domain), so the per-cycle
                         figure MUST be rescaled as bytes_per_sec / F_LOCK
                         whenever F_LOCK changes.

Hand-editing freq_GHz without rescaling the bandwidth terms silently changes
the machine's roofline balance point and corrupts every T_SOL. Hence: generate.

Consequence worth exploiting: because MAC_per_cycle is frequency-independent
and bandwidth is frequency-independent in absolute terms, the SOL bound in
CYCLES is invariant to F_LOCK. You can run SOLAR over all 235 problems today,
cache T_SOL in cycles, and convert to milliseconds with a single scalar
division once F_LOCK is measured on real silicon.

Usage:
    python gen_arch_yaml.py --part MI350X --freq-ghz 1.5 -o MI350X.yaml
    python gen_arch_yaml.py --part MI355X --freq-ghz 1.65 -o MI355X.yaml

The part table lives in ``solexbench_rocm.parts``, which is the single source
of truth for every AMD hardware constant in the project. It separates
ARCHITECTURAL figures (shared across parts on the same die, and cross-checked
against both parts' published peaks) from PART figures (peak clock, power cap
-- never shared) and MEASURED ones (F_LOCK -- never shared, never guessed).
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from solexbench_rocm.parts import PARTS

def gen(part_key: str, freq_ghz: float) -> str:
    p = PARTS[part_key]
    hz = freq_ghz * 1e9
    lines = [
        "# SPDX-License-Identifier: Apache-2.0",
        f"# SOLAR arch config for AMD Instinct {p.name}.",
        "# GENERATED by gen_arch_yaml.py -- do not hand-edit freq_GHz.",
        "# Re-run the generator to change the locked clock; bandwidth terms",
        "# are rescaled automatically.",
        "#",
        f"# Part: {p.name} ({p.gfx}, {p.compute_units} CU, {p.power_cap_w} W, "
        f"{p.cooling}-cooled)",
        f"# Locked clock: {freq_ghz} GHz  ({freq_ghz / p.peak_freq_ghz * 100:.1f}% of "
        f"{p.peak_freq_ghz} GHz peak)",
        "",
        f'name: "{p.name}"',
        f"freq_GHz: {freq_ghz}",
        "",
        "# --- capacity (frequency-independent) ---",
        f"SRAM_capacity: {p.llc_capacity}  # {p.llc_capacity // 2**20} MB last-level (Infinity Cache)",
        f"DRAM_capacity: {p.dram_capacity}  # {p.dram_capacity // 2**30} GB HBM",
        "",
        "# --- bandwidth (DERIVED: bytes_per_sec / freq) ---",
        f"SRAM_byte_per_cycle: {p.llc_bytes_per_sec / hz:.1f}  "
        f"# {p.llc_bytes_per_sec / 1e12:.1f} TB/s @ {freq_ghz} GHz  [PLACEHOLDER - verify]",
        f"DRAM_byte_per_cycle: {p.dram_bytes_per_sec / hz:.1f}  "
        f"# {p.dram_bytes_per_sec / 1e12:.1f} TB/s @ {freq_ghz} GHz",
        "",
        "# --- compute (ARCHITECTURAL: frequency-independent, do not rescale) ---",
    ]
    for k, v in p.mac_per_cycle.items():
        pflops = v * 2 * hz / 1e15
        unit = "POPS" if "int" in k else "PFLOPS"
        lines.append(f"MAC_per_cycle_{k}: {v}  # @ {freq_ghz} GHz: {pflops:.3f} {unit}")
    for alias, target in p.aliases.items():
        v = p.mac_per_cycle[target]
        lines.append(
            f"MAC_per_cycle_{alias}: {v}  # alias -> {target}; see note in parts.py"
        )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--part", required=True, choices=sorted(PARTS))
    ap.add_argument("--freq-ghz", type=float, required=True)
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    out = gen(a.part, a.freq_ghz)
    if a.out:
        with open(a.out, "w") as f:
            f.write(out)
        print(f"wrote {a.out}")
    else:
        print(out, end="")
