#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Task 03 — analytic Speed-of-Light bounds for every problem and workload.

Runs SOLAR's five-stage pipeline (graph -> einsum -> analysis -> roofline) over
each problem's own reference, wrapped as the `nn.Module` + `get_inputs()` pair
SOLAR expects.

    python scripts/sol_bounds.py --part MI350X --freq-mhz 1350 \
        --out artifacts/03/t_sol.json --jobs 64

Two properties of the output are worth stating up front, because they are what
make this cheap to redo:

**T_SOL is emitted in CYCLES as well as milliseconds.** MAC/cycle is
architectural and bandwidth is fixed in bytes/second, so the cycle count does
not depend on F_LOCK at all. If F_LOCK is ever re-measured, the millisecond
column is one scalar division away instead of a full re-run — and the cycle
column is directly comparable between MI350X and MI355X, which differ only in
clock.

**Every record states the clock its millisecond column was expressed at**, in
`f_ref_mhz`, and the header states it too — derived from the arch config that
was actually used, not from `--freq-mhz`. The two are not the same claim: a
`--resume` reuses a cached per-problem result computed at whatever clock that
run used, so an invocation's `--freq-mhz` describes the invocation and the
records describe the cache. `artifacts/03-MI355X/t_sol.json` shipped with those
two disagreeing — a header of 2400 over 2902 records at 1800 — and two later
consumers read the column as if one clock described it (docs/findings.md D63).
A body this script did not recompute can no longer be restamped: a cached
result at another clock is not a cache hit, and a body that still ends up mixed
leaves the header `null` rather than picking one of its clocks.

**Workloads are deduplicated by shape signature.** SOLAR's answer depends only
on shapes and dtypes, so two workloads that resolve to the same signature get
one pipeline run and share the result. Across the dataset this is roughly a 2x
saving and changes no number.

No GPU is used. Every tensor is allocated on `meta`, so a 28672-wide GEMM costs
no memory and the whole sweep runs on CPU cores.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
import traceback

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "scripts" / "runners"))
sys.path.insert(0, str(ROOT / "src"))

from provenance import write_artifact  # noqa: E402

# torch dtype -> the precision key SOLAR resolves MAC_per_cycle_<key>_tc and
# bytes-per-element from. Only keys SOLAR knows are emitted; an unmapped dtype
# is reported rather than silently coerced to fp32, because a wrong precision
# changes both the compute peak and the byte count.
DTYPE_TO_PRECISION = {
    "torch.float64": "fp64",
    "torch.float32": "fp32",
    "torch.bfloat16": "bf16",
    "torch.float16": "fp16",
    "torch.float8_e4m3fn": "fp8",
    "torch.float8_e5m2": "fp8",
    "torch.int8": "int8",
    "torch.uint8": "int8",
    # MXFP4 on CDNA4. SOLAR maps float4_e2m1fn_x2 -> "nvfp4" by literal string
    # lookup, and the generated AMD arch config carries an `nvfp4_tc` alias
    # pointing at the MXFP4 rate. The alias is a plumbing detail, NOT a claim
    # that the formats are equivalent -- they are not (block 16 vs 32, E4M3 vs
    # E8M0 scales), which is why task 07 respecs those problems.
    "torch.float4_e2m1fn_x2": "nvfp4",
}

# Precision ranking, narrowest first. The choice of END matters and the
# original one was wrong in the direction that breaks the bound.
#
# T_SOL is a LOWER bound, so every term in it must be a lower bound: the
# fastest rate the hardware could plausibly run this arithmetic at, and the
# least traffic it could plausibly move. Picking the WIDEST dtype present did
# the opposite for compute. In SOLAR's config `fp32` is
# `MAC_per_cycle_fp32_sm` -- the VECTOR rate, 32768 MAC/cycle, 16x below the
# bf16 matrix rate -- so a bf16 kernel with one float32 scalar argument was
# priced at 0.085 PFLOPS instead of 1.36. That is not a conservative bound, it
# is an impossible one: 437 workloads came out with T_SOL ABOVE their measured
# time, up to 13.4x, and 160 of the 235 problems resolved to fp32 this way.
#
# The narrowest floating type present is the rate the matmuls actually run at
# on a mixed-precision kernel, and it is the correct end of the ranking for a
# lower bound.
_PRECISION_RANK = ["nvfp4", "fp8", "int8", "fp16", "bf16", "tf32", "fp32", "fp64"]

MODEL_TEMPLATE = '''\
{reference}

# ---- SOLAR harness wrapper (generated by scripts/sol_bounds.py) ----
import torch as _solb_torch
import torch.nn as _solb_nn


class Model(_solb_nn.Module):
    """SOLAR entry point: the problem's own reference, unmodified."""

    def forward(self, *args):
        return run(*args)


def get_inputs():
    return [
{inputs}
    ]


def get_init_inputs():
    return []
'''


def _mhz(freq_ghz: float) -> float:
    """GHz -> MHz as a float, rounded so the value can be compared for equality.

    The clocks in use here happen to survive a bare `* 1000` intact (`2.4` and
    `1.8` both land exactly on 2400.0 and 1800.0), but that is a property of
    those two numbers and not of the operation: `1.005 * 1000` is
    `1004.9999999999999`. This field is compared for EQUALITY -- header against
    every record, and one tier's stamp against the other's -- so two spellings
    of one frequency reading as two clocks would invent exactly the disagreement
    the field exists to detect.
    """
    return round(float(freq_ghz) * 1000.0, 6)


def _record_f_refs(result: dict) -> set:
    """Every distinct `f_ref_mhz` among *result*'s bounded workloads.

    `None` is a member like any other and means "this record does not say" —
    which is the state that produced D63 and must not collapse into agreement
    with whatever the caller believes the clock to be.
    """
    return {w.get("f_ref_mhz")
            for w in (result.get("workloads") or {}).values()
            if w.get("t_sol_ms") is not None}


def _resume_clock_mismatch(prior: dict, f_ref_mhz: float) -> str | None:
    """Why *prior* cannot be reused at *f_ref_mhz*, or None if it can.

    The per-problem cache is keyed by PROBLEM, not by problem-and-clock, so a
    resume happily hands back a body computed at another frequency and the run
    that reused it goes on to describe the whole file with its own `--freq-mhz`.
    That is the mechanism on record for `artifacts/03-MI355X/t_sol.json` (D63),
    and it is cheap to close: a cached result at a different clock is simply not
    a hit, and neither is one that does not say. Both re-run — SOLAR is CPU work
    on `device="meta"`, and a wrong bound is not recoverable while a repeated
    derivation is only slow.
    """
    seen = _record_f_refs(prior)
    if not seen or seen == {f_ref_mhz}:
        return None
    if None in seen:
        return "cached before f_ref_mhz was recorded"
    return f"cached at {sorted(v for v in seen if v is not None)} MHz"


def _header_f_ref(results: dict,
                  arch_f_ref_mhz: float) -> tuple[float | None, list, int]:
    """(header `f_ref_mhz`, distinct stamps found, count of unstamped records).

    The header is allowed to state a clock only when every bounded record in
    the file agrees with the arch config the run derived against. Anything else
    -- two clocks, or a record that does not say -- and it states `null`, which
    the task-03 gate reads as a failure. That is the point: the alternative is a
    header that describes the invocation while the body describes a cache, which
    is what shipped (docs/findings.md D63) and which no reader could detect.

    Deriving it from the arch YAML rather than from `--freq-mhz` matters for the
    same reason. `--freq-mhz` is what this run asked for; the arch config is what
    the numbers were actually computed from, and the two are checked against each
    other in `main` before anything runs.
    """
    # Counted over RECORDS, not problems: 96 of 2998 was the whole of the
    # internal split that went unnoticed, and a per-problem count would have
    # reported it as six.
    stamps: set = set()
    unstamped = 0
    for r in results.values():
        for w in (r.get("workloads") or {}).values():
            if w.get("t_sol_ms") is None:
                continue
            f = w.get("f_ref_mhz")
            if f is None:
                unstamped += 1
            else:
                stamps.add(f)
    observed = sorted(stamps)
    ok = not unstamped and set(observed) <= {arch_f_ref_mhz}
    return (arch_f_ref_mhz if ok else None), observed, unstamped


def _torch_dtype_str(dtype) -> str:
    from sol_execbench.core.data.dtypes import dtype_str_to_torch_dtype

    value = dtype if isinstance(dtype, str) else getattr(dtype, "value", str(dtype))
    return str(dtype_str_to_torch_dtype(value))


def _precision_for(definition) -> tuple[str, list[str]]:
    """(precision key, unmapped dtypes) for a problem's TENSOR inputs.

    Scalars are excluded. A `float32` epsilon or dropout probability rides in a
    kernel argument; it is not the precision the arithmetic runs in, and
    letting it decide the rate priced most of the benchmark at the vector-FP32
    peak.
    """
    seen, unmapped = [], []
    for spec in definition.inputs.values():
        if getattr(spec, "shape", None) is None:
            continue                       # scalar: not a compute precision
        ds = _torch_dtype_str(spec.dtype)
        p = DTYPE_TO_PRECISION.get(ds)
        if p is None:
            unmapped.append(ds)
        elif p not in seen:
            seen.append(p)
    if not seen:
        return "fp32", unmapped
    # Narrowest, not widest -- see the note on _PRECISION_RANK. Integer inputs
    # (indices, offsets) are not a compute precision either, so they only
    # decide the answer when nothing else is present.
    floats = [p for p in seen if p != "int8"] or seen
    return min(floats, key=lambda p: _PRECISION_RANK.index(p)), unmapped


def _signature(definition, workload) -> str:
    shapes = definition.get_input_shapes(workload.axes)
    return json.dumps(
        [[k, None if v is None else [int(x) for x in v],
          _torch_dtype_str(definition.inputs[k].dtype)]
         for k, v in shapes.items()],
        sort_keys=True,
    )


def _scalar_value(workload, resolved_axes, name):
    """The value for a scalar input, from the workload if it states one."""
    spec = workload.inputs.get(name)
    value = getattr(spec, "value", None)
    if value is not None:
        return value
    if name in (resolved_axes or {}):
        return resolved_axes[name]
    return 0


def _model_source(definition, workload, mode: str = "meta") -> str:
    """SOLAR model file for one workload.

    Two tiers, and which one ran is RECORDED per workload:

      meta      -- free. No memory is allocated even for a 28672-wide GEMM,
                   because SOLAR only ever needs shapes and dtypes.
      cpu_real  -- the problem's OWN input generator, on CPU. Needed because a
                   reference that calls `.item()` or `nonzero()` is
                   data-dependent and simply cannot run on meta tensors --
                   `Tensor.item() cannot be called on meta tensors`. That is
                   688 of 3281 workloads, concentrated in the MoE routing and
                   variable-length-attention problems.

    The fallback deliberately uses REAL generated inputs rather than zeros on
    CPU. A zero-filled `cu_seqlens` traces an attention over nothing, and the
    resulting graph would yield a confident, wrong, much smaller bound. A
    missing bound is recoverable; a wrong one is not.
    """
    if mode == "cpu_real":
        return _model_source_cpu_real(definition, workload)
    shapes = definition.get_input_shapes(workload.axes)
    resolved = definition.get_resolved_axes_values(workload.axes)
    lines = []
    for name, shape in shapes.items():
        dt = _torch_dtype_str(definition.inputs[name].dtype)
        if shape is None:
            # A SCALAR input (`shape: null`) -- e.g. a dropout probability.
            # It must be passed as a Python number, not a 0-d tensor: the
            # reference uses it in control flow and arithmetic, and a meta
            # tensor there raises or, worse, silently changes the traced
            # graph. The value comes from the workload when it names one, and
            # otherwise defaults to 0, which is the value that keeps a
            # dropout/eps-style scalar from altering the op mix.
            value = _scalar_value(workload, resolved, name)
            lines.append(f"        {value!r},")
            continue
        # `device="meta"` is what makes this free: SOLAR only ever needs
        # shapes and dtypes, never values, so no memory is allocated even for
        # a 28672-wide GEMM.
        lines.append(
            f'        _solb_torch.zeros({[int(s) for s in shape]}, '
            f'dtype={dt}, device="meta"),'
        )
    return MODEL_TEMPLATE.format(
        reference=definition.reference, inputs="\n".join(lines)
    )


CPU_REAL_TEMPLATE = '''\
{reference}

# ---- SOLAR harness wrapper, real-input tier (generated by sol_bounds.py) ----
# This problem's reference is data-dependent (.item(), nonzero(), ...) and
# cannot be traced on meta tensors, so its own generator supplies real values
# on CPU. Shapes and dtypes are identical to the meta tier; only the values
# differ, and SOLAR uses only shapes and dtypes.
import json as _solb_json
import sys as _solb_sys

_solb_sys.path[:0] = [{scripts!r}, {runners!r}, {src!r}]

import torch as _solb_torch
import torch.nn as _solb_nn

from _common import exec_reference, load_problem, prepare_inputs as _solb_prepare


class Model(_solb_nn.Module):
    def forward(self, *args):
        return run(*args)


def get_inputs():
    _d, _wls = load_problem(__import__("pathlib").Path({problem!r}))
    _wl = [w for w in _wls if w.uuid == {uuid!r}][0]
    _run, _ns = exec_reference(_d)
    return _solb_prepare(_d, _wl, _ns, device="cpu")


def get_init_inputs():
    return []
'''


def _model_source_cpu_real(definition, workload) -> str:
    return CPU_REAL_TEMPLATE.format(
        reference=definition.reference,
        scripts=str(ROOT / "scripts"),
        runners=str(ROOT / "scripts" / "runners"),
        src=str(ROOT / "src"),
        problem=str(_PROBLEM_DIR[0]),
        uuid=workload.uuid,
    )


# The cpu_real template needs the problem directory, which `_model_source`
# does not receive. Set once per problem in `do_problem`; this module runs one
# problem per process (see `_fanout`), so a module-level slot is unambiguous.
_PROBLEM_DIR: list = [None]


def run_pipeline(model_src: str, workdir: Path, arch_yaml: Path,
                 precision: str) -> dict:
    """SOLAR stages 1-4 for one shape signature. Returns the perf dict."""
    from solar.analysis import EinsumGraphAnalyzer
    from solar.einsum import PyTorchToEinsum
    from solar.graph import PyTorchProcessor
    from solar.perf import EinsumGraphPerfModel

    # AMD: SOLAR reads `groups` from `module_args`, which is populated only for
    # nn.Module convolutions. Every convolution in this benchmark is functional,
    # so `groups` never arrived and a grouped conv was priced as a dense one --
    # 768x on L1__006's arithmetic term, to the digit. Applied explicitly here
    # rather than on import so that whether a bound carries the correction is a
    # property of the code that produced it. See D37 and
    # `solexbench_rocm/solar/conv_groups.py`.
    from solexbench_rocm.solar import conv_groups

    conv_groups.apply()

    workdir.mkdir(parents=True, exist_ok=True)
    model_file = workdir / "model.py"
    model_file.write_text(model_src)

    PyTorchProcessor().process_model_file(str(model_file),
                                          output_dir=str(workdir / "graph"))
    graph = workdir / "graph" / "pytorch_graph.yaml"
    if not graph.exists():
        raise RuntimeError("SOLAR stage 1 produced no pytorch_graph.yaml")

    PyTorchToEinsum().convert(str(graph), str(workdir / "einsum"),
                              copy_graph=False)
    einsum = workdir / "einsum" / "einsum_graph_renamed.yaml"
    if not einsum.exists():
        raise RuntimeError("SOLAR stage 2 produced no einsum_graph_renamed.yaml")

    EinsumGraphAnalyzer().analyze_graph(str(einsum), str(workdir / "analysis"),
                                        precision=precision)
    analysis = workdir / "analysis" / "analysis.yaml"
    if not analysis.exists():
        raise RuntimeError("SOLAR stage 3 produced no analysis.yaml")

    perf = EinsumGraphPerfModel().predict(
        str(analysis), str(workdir / "perf"),
        arch_config=str(arch_yaml), precision=precision,
    )
    if not perf:
        raise RuntimeError("SOLAR stage 4 returned no prediction")
    return perf


def do_problem(args) -> tuple[str, dict]:
    problem, arch_yaml, scratch, freq_ghz = args
    key = f"{problem.parent.name}__{problem.name}"
    out: dict = {"problem": key, "workloads": {}}
    try:
        import shutil

        from _common import load_problem

        definition, workloads = load_problem(problem)
        precision, unmapped = _precision_for(definition)
        out["precision"] = precision
        out["definition"] = definition.name
        if unmapped:
            # Recorded, not silently defaulted: an unmapped dtype means the
            # bound below was computed at the wrong peak.
            out["unmapped_dtypes"] = sorted(set(unmapped))

        _PROBLEM_DIR[0] = problem
        cache: dict[str, tuple[dict, str]] = {}
        for wl in workloads:
            sig = _signature(definition, wl)
            try:
                if sig not in cache:
                    errors = []
                    for mode in ("meta", "cpu_real"):
                        wd = scratch / key / f"{abs(hash(sig))}_{mode}"
                        try:
                            cache[sig] = (
                                run_pipeline(
                                    _model_source(definition, wl, mode),
                                    wd, arch_yaml, precision,
                                ),
                                mode,
                            )
                            break
                        except Exception as e:               # noqa: BLE001
                            errors.append(f"{mode}: {type(e).__name__}: {e}")
                        finally:
                            shutil.rmtree(wd, ignore_errors=True)
                    else:
                        raise RuntimeError(" | ".join(errors))
                perf, input_mode = cache[sig]
                fused = perf["fused"]
                unfused = perf["unfused"]
                # ceil, not truncate, and keep the exact figure beside it.
                # Truncating gave EIGHT workloads a T_SOL of zero cycles --
                # a "bound" of zero time, which no kernel can approach and
                # which puts a division by (T_b - 0) into the score. The
                # smallest workloads here are genuinely sub-cycle at 1.3 GHz
                # (12 KB at 8 TB/s is about 2 cycles), so the rounding is not
                # a rare edge: it is the normal case at the small end.
                #
                # SOLAR's own `total_cycles` is already `int(...)`-truncated,
                # so it cannot be un-rounded -- the roofline is recomputed here
                # from the same quantities SOLAR used (its arch block is
                # emitted alongside the result), which is its formula exactly:
                # max(MACs/MAC_per_cycle, bytes/DRAM_byte_per_cycle).
                _arch = perf["arch"]
                _mac_pc = float(_arch.get("MAC_per_cycle") or 0.0)
                _dram_bw = float(_arch.get("DRAM_byte_per_cycle") or 0.0)
                _macs = float(perf["workload"]["total_macs"])
                _compute_cycles = _macs / _mac_pc if _mac_pc > 0 else 0.0
                _memory_cycles = (float(fused["memory_bytes"]) / _dram_bw
                                  if _dram_bw > 0 else 0.0)
                exact_cycles = max(_compute_cycles, _memory_cycles)
                cycles = max(1, math.ceil(exact_cycles))
                # The two terms are kept SEPARATELY, not just their max, because the
                # two scale differently with the clock, and a node that cannot pin a
                # clock has no single frequency to evaluate at: every timing happens
                # the card chose for that kernel, so the bound has to be evaluated
                # at that frequency. Per the arch YAML's own annotations,
                # MAC_per_cycle is architectural and frequency-independent, while
                # DRAM_byte_per_cycle is derived as bytes_per_sec/freq. So in TIME:
                # the compute term scales as 1/F and the memory term does not scale
                # at all. Given only the max, neither could be recovered, and the
                # bottleneck can flip as F moves -- which is why both are emitted
                # along with the frequency-independent constants needed to
                # re-evaluate them. See t_sol_at() in src/solexbench_rocm/t_sol_at.py.
                _dram_byte_per_sec = _dram_bw * freq_ghz * 1e9
                out["workloads"][wl.uuid] = {
                    # THE bound. `fused` is the model that matches what a good
                    # kernel actually does -- intermediates stay on chip. The
                    # unfused figure is kept alongside as the weak bound, so a
                    # T_SOL <= measured violation can be diagnosed rather than
                    # just observed.
                    "t_sol_cycles": cycles,
                    # The un-rounded figure, so that a future consumer can see
                    # how much of a small bound is rounding.
                    "t_sol_cycles_exact": exact_cycles,
                    "t_sol_ms": cycles / (freq_ghz * 1e6),
                    # The clock the two columns above were expressed at, on the
                    # record rather than only in the header. A cycle count is
                    # meaningless next to any other frequency, and a header is
                    # a claim about a whole file that a resume can make about a
                    # body it did not compute -- which is how one file came to
                    # hold two clocks under one header (docs/findings.md D63).
                    # `src/solexbench_rocm/t_sol_at.bound_ms` refuses a record
                    # without it.
                    "f_ref_mhz": _mhz(freq_ghz),
                    "bottleneck": fused["bottleneck"],
                    # Frequency-independent bound terms, for re-evaluating T_SOL at
                    # the clock a measurement actually ran at.
                    "compute_cycles": _compute_cycles,
                    "memory_cycles_at_f_ref": _memory_cycles,
                    "mac_per_cycle": _mac_pc,
                    "dram_byte_per_sec": _dram_byte_per_sec,
                    "unfused_cycles": max(1, math.ceil(float(unfused["total_cycles"]))),
                    "macs": int(perf["workload"]["total_macs"]),
                    "memory_bytes": int(fused["memory_bytes"]),
                    "arithmetic_intensity": fused["arithmetic_intensity"],
                    "axes": dict(wl.axes),
                    "input_mode": input_mode,
                    "shared_signature": sig if len(cache) else None,
                }
            except Exception as e:                    # noqa: BLE001
                out["workloads"][wl.uuid] = {
                    "error": f"{type(e).__name__}: {e}",
                    "axes": dict(wl.axes),
                }

        ok = [w for w in out["workloads"].values() if "t_sol_cycles" in w]
        out["n_ok"], out["n_workloads"] = len(ok), len(workloads)
        out["unique_signatures"] = len(cache)
        out["status"] = "ok" if ok else "failed"
        return key, out
    except Exception as e:                            # noqa: BLE001
        out["status"] = "failed"
        out["error"] = f"{type(e).__name__}: {e}"
        out["traceback"] = traceback.format_exc()[-2000:]
        return key, out


def _fanout(problems, arch_yaml, scratch, freq_ghz, jobs, timeout, resume=False,
            only_status=None):
    """One subprocess per problem, with a hard timeout.

    Not a process pool: SOLAR's stage 1 traces arbitrary reference code, and
    some references trace pathologically (deep unrolled loops, tensor
    construction in the forward). A pool worker stuck in that cannot be
    cancelled, and one such problem would stall the whole sweep behind it —
    the classic way a "finished" sweep silently covers 200 problems instead of
    235. A subprocess can simply be killed, and the timeout recorded as the
    result it is.
    """
    import subprocess
    from concurrent.futures import ThreadPoolExecutor

    f_ref_mhz = _mhz(freq_ghz)
    rejected: list[tuple[str, str]] = []

    def one(problem: Path):
        key = f"{problem.parent.name}__{problem.name}"
        out_file = scratch / "per-problem" / f"{key}.json"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        if resume and out_file.exists():
            # Resume skips only problems that SUCCEEDED. A failure is re-run,
            # because the common reason to re-run at all is a longer timeout,
            # and skipping recorded failures would silently freeze the gap in
            # place while looking like a completed sweep.
            #
            # ...and only problems whose bounds are already at THIS clock. The
            # cache is keyed by problem alone, so without this a resume at one
            # frequency serves a body derived at another and the run stamps its
            # own frequency over the file (D63).
            try:
                prior = json.loads(out_file.read_text())
                if prior.get("status") == "ok":
                    why = _resume_clock_mismatch(prior, f_ref_mhz)
                    if why is None:
                        return key, prior
                    rejected.append((key, why))
            except Exception:                          # noqa: BLE001
                pass
        if only_status is not None:
            # Re-run exactly one class of prior result and leave the rest
            # alone. `--only-status ok` refreshes every bound that succeeded
            # after a change to how the bound is computed, without paying
            # again for the failures -- which are the slow ones, because a
            # failure usually means SOLAR ran to the timeout.
            try:
                prior = json.loads(out_file.read_text())
            except Exception:                          # noqa: BLE001
                return key, {"problem": key, "status": "failed",
                             "error": "no prior result to refresh"}
            if prior.get("status") != only_status:
                return key, prior
        cmd = [
            sys.executable, str(Path(__file__).resolve()),
            "--one", str(problem), "--out", str(out_file),
            "--arch-yaml", str(arch_yaml), "--part", "x",
            "--freq-mhz", str(int(round(freq_ghz * 1000))),
            "--scratch", str(scratch),
        ]
        try:
            subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired:
            return key, {"problem": key, "status": "failed",
                         "error": f"timeout after {timeout}s in SOLAR pipeline"}
        try:
            return key, json.loads(out_file.read_text())
        except Exception as e:                        # noqa: BLE001
            return key, {"problem": key, "status": "failed",
                         "error": f"no result file: {type(e).__name__}: {e}"}

    with ThreadPoolExecutor(max_workers=jobs) as ex:
        for i, (key, res) in enumerate(ex.map(one, problems), 1):
            if i % 25 == 0:
                print(f"  {i}/{len(problems)}", flush=True)
            yield key, res

    if rejected:
        print(f"\n{len(rejected)} cached result(s) re-run rather than resumed: "
              f"their bounds are not at {f_ref_mhz} MHz", file=sys.stderr)
        for key, why in rejected[:10]:
            print(f"  {key}: {why}", file=sys.stderr)
        if len(rejected) > 10:
            print(f"  ... and {len(rejected) - 10} more", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/SOL-ExecBench/benchmark")
    ap.add_argument("--out", default="artifacts/03/t_sol.json")
    ap.add_argument("--one", type=Path, default=None,
                    help="internal: run a single problem and write its JSON")
    ap.add_argument("--only-status", choices=["ok", "failed"], default=None,
                    help="re-run only problems whose recorded status is this. "
                         "`ok` refreshes successful bounds after a change to "
                         "how the bound is computed, without paying again for "
                         "the failures, which are the slow ones.")
    ap.add_argument("--resume", action="store_true",
                    help="skip problems that already succeeded; re-run "
                         "failures (which is the point of resuming)")
    ap.add_argument("--timeout", type=int, default=900,
                    help="per-problem wall clock before it is recorded as a "
                         "timeout and the sweep moves on")
    ap.add_argument("--part", required=True,
                    help="MI350X or MI355X — selects the arch constants")
    ap.add_argument("--freq-mhz", type=int, required=True,
                    help="F_LOCK in MHz, MEASURED (tasks/01). Only the ms "
                         "column depends on it; cycles do not.")
    ap.add_argument("--arch-yaml", default=None,
                    help="default: SOLAR/configs/arch/<part>.yaml, generated")
    ap.add_argument("--jobs", type=int, default=32)
    ap.add_argument("--scratch", type=Path,
                    default=Path("/var/tmp/solbench/sol-scratch"),
                    help="per-problem result cache (what --resume reads). Point "
                         "it elsewhere for a trial run: the default holds the "
                         "cache a real sweep resumes from, and overwriting that "
                         "is how a body ends up at a clock nobody chose.")
    ap.add_argument("--category", nargs="+",
                    default=["L1", "L2", "Quant", "FlashInfer-Bench"])
    a = ap.parse_args()

    freq_ghz = a.freq_mhz / 1000.0
    scratch = Path(a.scratch)

    arch_yaml = Path(a.arch_yaml) if a.arch_yaml else (
        ROOT / "SOLAR" / "configs" / "arch" / f"{a.part}.yaml")
    if not arch_yaml.exists():
        sys.exit(
            f"arch config missing: {arch_yaml}\n"
            f"Generate it first (it must be generated, not hand-written — the "
            f"bandwidth terms rescale with F_LOCK):\n"
            f"  python src/solexbench_rocm/solar/gen_arch_yaml.py "
            f"--part {a.part} --freq-ghz {freq_ghz} -o {arch_yaml}"
        )

    import yaml
    arch = yaml.safe_load(arch_yaml.read_text())
    if abs(float(arch["freq_GHz"]) - freq_ghz) > 1e-9:
        sys.exit(
            f"arch config is at {arch['freq_GHz']} GHz but --freq-mhz says "
            f"{freq_ghz} GHz. Regenerate it; do not hand-edit freq_GHz, which "
            f"would leave the bandwidth terms at the old clock and corrupt "
            f"every memory-bound T_SOL."
        )
    # Checked before the `--one` branch as well as the sweep: a single-problem
    # run writes records stamped `f_ref_mhz` from `--freq-mhz` while their
    # memory term comes from the arch YAML, so the two disagreeing would make
    # the stamp itself a false statement.
    arch_f_ref_mhz = _mhz(arch["freq_GHz"])

    if a.one is not None:
        key, res = do_problem((a.one, arch_yaml, scratch, freq_ghz))
        Path(a.out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.out).write_text(json.dumps(res, default=str))
        return

    data = Path(a.data)
    problems = [p for c in a.category for p in sorted((data / c).glob("*"))
                if (p / "definition.json").exists()]
    print(f"{len(problems)} problems, {a.jobs} workers, {a.part} @ {a.freq_mhz} MHz")

    results = {}
    for key, res in _fanout(problems, arch_yaml, scratch, freq_ghz,
                            a.jobs, a.timeout, resume=a.resume,
                            only_status=a.only_status):
        results[key] = res

    n_wl = sum(r.get("n_workloads", 0) for r in results.values())
    n_ok = sum(r.get("n_ok", 0) for r in results.values())
    header_f_ref, observed, unstamped = _header_f_ref(results, arch_f_ref_mhz)
    if header_f_ref is None:
        print(f"\nWARNING: this file's bounds are not all on one clock, so its "
              f"header states none. Records at {observed} MHz"
              + (f", {unstamped} with no f_ref_mhz at all" if unstamped else "")
              + f"; the arch config used is at {arch_f_ref_mhz} MHz. Re-derive "
              f"without --resume/--only-status before publishing it: a mixed "
              f"file is what docs/findings.md D63 is about.", file=sys.stderr)
    payload = {
        "part": a.part,
        # NOT `f_lock_mhz`. This is the clock the millisecond column was
        # expressed at, which is a property of the derivation and of the arch
        # config it used -- not a claim that a clock was pinned. MI355X cannot
        # pin one at all, and the old name asserted otherwise on every artifact
        # derived for it. `null` here means the body holds more than one clock
        # and the header refuses to pick; the per-record `f_ref_mhz` is then
        # the only truthful reading.
        "f_ref_mhz": header_f_ref,
        "f_ref_mhz_observed": observed,
        "f_ref_mhz_unstamped_records": unstamped,
        "arch_yaml": str(arch_yaml),
        "sol_model": "fused",
        "n_problems": len(results),
        "n_problems_ok": sum(1 for r in results.values() if r.get("status") == "ok"),
        "n_workloads": n_wl,
        "n_workloads_ok": n_ok,
        "problems": results,
    }
    # `--part` is required above and already selects the arch YAML, so it is the
    # part this file's every byte is about. Declaring it to the stamper as well
    # gets the cross-check against the visible cards for free: a `--part MI350X`
    # run on this node now raises instead of writing MI350X rooflines into an
    # artifact that every inference path would read as MI355X. Pass
    # `allow_cross_part=True` only if deriving one part's bounds on the other's
    # node is genuinely what is meant.
    write_artifact(a.out, "03-sol-bounds", payload, part=a.part)
    print(f"\n{n_ok}/{n_wl} workload bounds, "
          f"{payload['n_problems_ok']}/{len(results)} problems -> {a.out}")
    if n_ok < n_wl:
        print("Gaps are recorded per workload with the SOLAR error that caused "
              "them. Run scripts/check_coverage.py before treating this as done.")


if __name__ == "__main__":
    main()
